services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/insights.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - SIMILARITY_THRESHOLD=0.8
      - MAX_THESIS_SENTENCES=2
      - LOG_LEVEL=INFO
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    restart: unless-stopped
